modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
logoFile="logo.png"

[[mods]]
modId="ucse"
version="${file.jarVersion}"
displayName="Unique Crops: Sandbox Edition"
logoFile="logo.png"
authors="bafomdad, Remag"
description="Unique crops, unique growth, unique drops"

[[dependencies.ucse]]
    modId="forge"
    mandatory=true #mandatory
    versionRange="[40.1.68,)"
	
[[dependencies.ucse]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.2-67,)"

[[dependencies.ucse]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.9.1,)"
